In [296]:
import numpy as np
import pandas as pd
import matplotlib_inline

In [297]:
x=pd.read_csv('training.csv')
x[:5]

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     w  120.362774  205.500000  119.395349  416.581395  20.676318
1     w  124.739583  202.800000  115.333333  354.333333  16.707151
2     w  134.691964  199.285714  116.857143  477.857143  22.496712
3     w  127.946309  178.368421   92.368421  278.473684  14.977453
4     w  135.431548  197.000000  112.690476  532.952381  17.604193

In [298]:
from  sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['class']=le.fit_transform(x['class'])
x['class']


0       1
1       1
2       1
3       1
4       1
       ..
4334    0
4335    0
4336    0
4337    0
4338    0
Name: class, Length: 4339, dtype: int64

In [299]:
feature=x[['GLCM_pan','Mean_Green','Mean_Red','Mean_NIR','SD_pan']]
feature[:10]

GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0  120.362774  205.500000  119.395349  416.581395  20.676318
1  124.739583  202.800000  115.333333  354.333333  16.707151
2  134.691964  199.285714  116.857143  477.857143  22.496712
3  127.946309  178.368421   92.368421  278.473684  14.977453
4  135.431548  197.000000  112.690476  532.952381  17.604193
5  118.347962  226.150000  138.850000  608.900000  29.072797
6  135.436282  184.500000   95.142857  309.190476  13.055264
7  121.169643  226.000000  146.214286  595.571429  22.808542
8  131.127161  232.784314  144.588235  563.843137  11.948563
9  134.498092  210.212121  116.909091  594.848485  27.937685

In [300]:
y=x['class'].values
y

array([1, 1, 1, ..., 0, 0, 0], shape=(4339,))

In [301]:
x=np.asanyarray(x)

In [302]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(feature,y,test_size=0.2,random_state=42)

print('set training data:',x_train.shape,y_train.shape)
print('set testing data:',x_test.shape,y_test.shape)

set training data: (3471, 5) (3471,)
set testing data: (868, 5) (868,)


In [323]:
from sklearn.preprocessing import PowerTransformer
scaler=PowerTransformer()
x_train1=scaler.fit_transform(x_train)
x_test1=scaler.transform(x_test)

In [324]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression().fit(x_train1,y_train)
regressor

LogisticRegression()

In [325]:
test_image=pd.read_csv('testing.csv')
test_image[:5]

class    GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0     n  109.828571  183.700000   82.950000  251.750000  16.079412
1     n  130.284483  212.637931   96.896552  482.396552  21.210295
2     n  131.386555  185.466667   85.466667  419.666667  13.339998
3     n  141.345098  180.875000   81.500000  348.062500  18.213577
4     w  121.383408  218.357143  112.017857  426.607143  19.083196

In [326]:
from  sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
test_image['class']=le.fit_transform(test_image['class'])
test_image['class']

0      0
1      0
2      0
3      0
4      1
      ..
495    0
496    0
497    0
498    0
499    0
Name: class, Length: 500, dtype: int64

In [327]:
c=test_image[['GLCM_pan','Mean_Green','Mean_Red','Mean_NIR','SD_pan']]
c[:5]

GLCM_pan  Mean_Green    Mean_Red    Mean_NIR     SD_pan
0  109.828571  183.700000   82.950000  251.750000  16.079412
1  130.284483  212.637931   96.896552  482.396552  21.210295
2  131.386555  185.466667   85.466667  419.666667  13.339998
3  141.345098  180.875000   81.500000  348.062500  18.213577
4  121.383408  218.357143  112.017857  426.607143  19.083196

In [328]:
yy2=test_image['class'].values
yy2

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,

In [329]:
test_image=np.asanyarray(test_image)

In [330]:
y_pred=regressor.predict(x_test1)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [332]:
from sklearn.metrics import r2_score ,accuracy_score,precision_score,recall_score


print('accuracy:',accuracy_score(y_test,y_pred))
print('precision_score:',precision_score(y_test,y_pred))
print('recall_score:',recall_score(y_test,y_pred))


accuracy: 0.9907834101382489
precision_score: 1.0
recall_score: 0.5789473684210527
